<a href="https://colab.research.google.com/github/SaikrishnaPulipati533/TERRABLUE_XT_PREDICT_EL_FUTURE/blob/master/terrablue_lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers.recurrent import LSTM
from keras.layers.core import Dense, Activation, Dropout
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.utils import shuffle

In [3]:
file= 'train_csv.csv'
data = pd.read_csv(file)
data.head()

id                 time  feature
0   0  2019-03-19 00:00:00   237.97
1   1  2019-03-19 00:00:10    57.93
2   2  2019-03-19 00:00:20    90.53
3   3  2019-03-19 00:00:30   260.75
4   4  2019-03-19 00:00:40    49.70

In [4]:
data.shape

(80, 3)

In [32]:
ts_data=data.iloc[:,2:3].values
#ts_data.head()

In [47]:
ts_data

array([[237.97],
       [ 57.93],
       [ 90.53],
       [260.75],
       [ 49.7 ],
       [302.08],
       [152.25],
       [ 41.19],
       [ 34.61],
       [205.87],
       [166.23],
       [ 73.75],
       [282.46],
       [122.71],
       [ 32.04],
       [ 40.73],
       [ 55.06],
       [ 46.4 ],
       [ 54.46],
       [ 29.97],
       [ 40.43],
       [ 21.36],
       [ 46.59],
       [ 43.11],
       [ 55.62],
       [ 27.36],
       [ 50.94],
       [116.61],
       [ 91.8 ],
       [198.32],
       [326.76],
       [266.69],
       [205.95],
       [149.42],
       [233.22],
       [ 63.63],
       [ 89.77],
       [255.79],
       [161.08],
       [123.41],
       [239.69],
       [108.12],
       [ 94.31],
       [224.3 ],
       [184.75],
       [113.74],
       [146.06],
       [326.35],
       [126.81],
       [192.  ],
       [187.7 ],
       [194.04],
       [293.84],
       [201.54],
       [123.67],
       [260.87],
       [ 28.26],
       [131.97],
       [ 76.73

In [33]:
scaler = MinMaxScaler(feature_range = (0, 1))
dataset = scaler.fit_transform(pd.DataFrame(ts_data))
# MinMaxScaler needs the data in 2D array , thats why the syntactical jugglery above

In [34]:
dataset.shape

(80, 1)

In [35]:
train_fraction = 0.60

train_size = int(len(dataset) * train_fraction)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]

In [36]:
print(train_size, test_size)

48 32


In [37]:
def create_dataset(dataset, window_size = 1):
    data_X, data_Y = [], []
    for i in range(len(dataset) - window_size - 1):
        a = dataset[i:(i + window_size), 0]
        data_X.append(a)
        data_Y.append(dataset[i + window_size, 0])
    return(np.array(data_X), np.array(data_Y))

In [38]:
window_size = 10

train_X, train_Y = create_dataset(train, window_size)
test_X, test_Y = create_dataset(test, window_size)

print("Original training data shape:")
print(train_X.shape)

Original training data shape:
(37, 10)


In [39]:
range(len(dataset) - window_size - 1)

range(0, 69)

In [40]:
pd.DataFrame(train_X).head()

0         1         2         3         4         5         6  \
0  0.483116  0.081564  0.154273  0.533924  0.063208  0.626104  0.291931   
1  0.081564  0.154273  0.533924  0.063208  0.626104  0.291931  0.044228   
2  0.154273  0.533924  0.063208  0.626104  0.291931  0.044228  0.029552   
3  0.533924  0.063208  0.626104  0.291931  0.044228  0.029552  0.411522   
4  0.063208  0.626104  0.291931  0.044228  0.029552  0.411522  0.323111   

          7         8         9  
0  0.044228  0.029552  0.411522  
1  0.029552  0.411522  0.323111  
2  0.411522  0.323111  0.116848  
3  0.323111  0.116848  0.582345  
4  0.116848  0.582345  0.226046

In [41]:
# shape of data should be : (num_obs, feature_dimension, sequence_length)
train_X = np.reshape(train_X, (train_X.shape[0], 1, train_X.shape[1]))
test_X = np.reshape(test_X, (test_X.shape[0], 1, test_X.shape[1]))

print("New training data shape:")
print(train_X.shape)

New training data shape:
(37, 1, 10)


In [42]:
# input shape : (feature_dimension, seq_length)
model = Sequential()
    
model.add(LSTM(4, 
               input_shape = (1, window_size)))
model.add(Dense(1))
model.compile(loss = "mean_squared_error", 
              optimizer = "adam")

model.fit(train_X, 
          train_Y, 
          epochs = 50, 
          batch_size = 1, 
          verbose = 2)

Epoch 1/50
 - 0s - loss: 0.0975
Epoch 2/50
 - 0s - loss: 0.0761
Epoch 3/50
 - 0s - loss: 0.0615
Epoch 4/50
 - 0s - loss: 0.0521
Epoch 5/50
 - 0s - loss: 0.0454
Epoch 6/50
 - 0s - loss: 0.0415
Epoch 7/50
 - 0s - loss: 0.0400
Epoch 8/50
 - 0s - loss: 0.0380
Epoch 9/50
 - 0s - loss: 0.0371
Epoch 10/50
 - 0s - loss: 0.0366
Epoch 11/50
 - 0s - loss: 0.0359
Epoch 12/50
 - 0s - loss: 0.0354
Epoch 13/50
 - 0s - loss: 0.0351
Epoch 14/50
 - 0s - loss: 0.0345
Epoch 15/50
 - 0s - loss: 0.0341
Epoch 16/50
 - 0s - loss: 0.0337
Epoch 17/50
 - 0s - loss: 0.0338
Epoch 18/50
 - 0s - loss: 0.0331
Epoch 19/50
 - 0s - loss: 0.0326
Epoch 20/50
 - 0s - loss: 0.0324
Epoch 21/50
 - 0s - loss: 0.0321
Epoch 22/50
 - 0s - loss: 0.0318
Epoch 23/50
 - 0s - loss: 0.0313
Epoch 24/50
 - 0s - loss: 0.0309
Epoch 25/50
 - 0s - loss: 0.0307
Epoch 26/50
 - 0s - loss: 0.0305
Epoch 27/50
 - 0s - loss: 0.0301
Epoch 28/50
 - 0s - loss: 0.0297
Epoch 29/50
 - 0s - loss: 0.0294
Epoch 30/50
 - 0s - loss: 0.0290
Epoch 31/50
 - 0s -

In [43]:
# Make predictions on the original scale of the data.
pred = scaler.inverse_transform(model.predict(train_X))

# Prepare Y data to also be on the original scale for interpretability.
orig_data = scaler.inverse_transform([train_Y])

# Calculate RMSE.
score_test = np.sqrt(mean_squared_error(orig_data[0], pred[:, 0]))

In [44]:
orig_data

array([[166.23,  73.75, 282.46, 122.71,  32.04,  40.73,  55.06,  46.4 ,
         54.46,  29.97,  40.43,  21.36,  46.59,  43.11,  55.62,  27.36,
         50.94, 116.61,  91.8 , 198.32, 326.76, 266.69, 205.95, 149.42,
        233.22,  63.63,  89.77, 255.79, 161.08, 123.41, 239.69, 108.12,
         94.31, 224.3 , 184.75, 113.74, 146.06]])

In [48]:
pred

array([[129.53839 ],
       [130.06337 ],
       [144.01283 ],
       [132.7648  ],
       [128.75562 ],
       [103.564026],
       [136.01582 ],
       [ 97.540924],
       [ 97.37693 ],
       [102.67657 ],
       [ 67.079216],
       [ 68.971375],
       [ 60.48803 ],
       [ 85.51859 ],
       [ 96.77779 ],
       [ 95.721115],
       [ 91.2488  ],
       [ 93.52977 ],
       [112.16014 ],
       [122.0339  ],
       [145.66673 ],
       [195.07771 ],
       [198.68085 ],
       [201.65526 ],
       [187.35593 ],
       [168.2193  ],
       [161.36444 ],
       [139.49315 ],
       [141.60788 ],
       [121.472115],
       [117.59842 ],
       [152.62762 ],
       [113.438644],
       [130.22234 ],
       [168.77235 ],
       [141.31119 ],
       [138.10355 ]], dtype=float32)

In [50]:
#print("Training data score: ",  score_train)
print("Test data score: ",  score_test)

Test data score:  68.3939538463071


In [66]:
pd.DataFrame(pred).to_csv("predict_feature.csv", index=False)